services:
  - type: web
    name: posifine-backend
    env: python
    buildCommand: pip install -r requirements.txt && gunicorn --version
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"