services:
  - type: web
    name: universal-pos-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/pos_db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production